apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: opendistro
spec:
  forProvider:
    chart:
      name: opendistro-es
      repository: https://mcbenjemaa.github.io/opendistro-build
      version: 1.13.3
    namespace: default
    values:
      kibana:
        service:
          type: ClusterIP
    set:
      - name: kibana.externalPort
        value: "80"
  providerConfigRef:
    name: helm-provider