apiVersion: container.gcp.crossplane.io/v1beta1
kind: GKECluster
metadata:
  name: sample-gke-cluster
spec:
  forProvider:
    location: us-east1
    initialClusterVersion: latest

---

apiVersion: container.gcp.crossplane.io/v1alpha1
kind: NodePool
metadata:
  name: sample-gke-noodepool
spec:
  forProvider:
    locations:
      - us-east1-b
    clusterRef:
      name: sample-gke-cluster
    initialNodeCount: 1
    config:
      preemptible: true
      machineType: e2-standard-2
      oauthScopes:
        - https://www.googleapis.com/auth/cloud-platform
    autoscaling:
      enabled: true
      minNodeCount: 1
      maxNodeCount: 2
    management:
      autoUpgrade: false