apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: opendistro-composition
  labels:
    purpose: example
    provider: helm
spec:
  # This Composition declares that it satisfies the CompositeMySQLInstance
  # resource defined above - i.e. it patches "from" a CompositeMySQLInstance.
  # Note that the version in apiVersion must be the referenceable version of the
  # XRD.
  compositeTypeRef:
    apiVersion: renault.fr/v1alpha1
    kind: CompositeOpendistro


  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels


  # resources.
  resources:
     - base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        metadata:
          name: opendistro
        spec:
          forProvider:
            chart:
              name: opendistro-es
              repository: https://mcbenjemaa.github.io/opendistro-build
              version: 1.13.3
            namespace: default
            values:
              kibana:
                externalPort: 443
                service:
                  type: ClusterIP

          providerConfigRef:
            name: helm-provider
       patches:
        - fromFieldPath: spec.kibanaService
          toFieldPath: spec.forProvider.values.kibana.service.type
        - fromFieldPath: spec.kibanaPort
          toFieldPath: spec.forProvider.values.kibana.externalPort