apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: crossplane-demo-simple-configuration
  annotations:
    guide: quickstart
    provider: helm
spec:
  crossplane:
    version: ">=v1.3.0-0"
  dependsOn:
    - provider: crossplane/provider-helm
      version: ">=v0.7.0"